---
# Rename file to secrets.yml to get started for development or test

development:
  API_URL: http://localhost:3000/api/v1
  SHORT_URL: http://localhost:3000
  APP_URL: http://localhost:9292
  SESSION_SECRET: ND3mZpWrmpAEEjke2N7eJn65IrUPLtCxwYSaql1b0L0+LgaxMPik2Eb9DEYsNSV4SWC4FCOdKtsQ8IIangRYDQ==
  MSG_KEY: kRKnnNKNeqiLHACCoiEysbhCnT/xUBJc81AFgT4VIao=
  REDIS_URL: xxx
  GOOGLE_API_CLIENT_ID: xxx
  GOOGLE_API_CLIENT_SECRET: xxx

test:
  API_URL: http://localhost:3000/api/v1
  SHORT_URL: http://localhost:3000
  APP_URL: http://localhost:9292
  SESSION_SECRET: ND3mZpWrmpAEEjke2N7eJn65IrUPLtCxwYSaql1b0L0+LgaxMPik2Eb9DEYsNSV4SWC4FCOdKtsQ8IIangRYDQ==
  MSG_KEY: kRKnnNKNeqiLHACCoiEysbhCnT/xUBJc81AFgT4VIao=
  REDIS_URL: xxx
  GOOGLE_API_CLIENT_ID: xxx
  GOOGLE_API_CLIENT_SECRET: xxx

production:
  API_URL: http://localhost:3000/api/v1
  SHORT_URL: http://localhost:3000
  APP_URL: http://localhost:9292
  SESSION_SECRET: ND3mZpWrmpAEEjke2N7eJn65IrUPLtCxwYSaql1b0L0+LgaxMPik2Eb9DEYsNSV4SWC4FCOdKtsQ8IIangRYDQ==
  MSG_KEY: kRKnnNKNeqiLHACCoiEysbhCnT/xUBJc81AFgT4VIao=
  REDIS_URL: xxx
  GOOGLE_API_CLIENT_ID: xxx
  GOOGLE_API_CLIENT_SECRET: xxx
